name: Package
on:
  release:
    types: [ created ]
jobs:
  package-android:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: gradle/actions/setup-gradle@v4
      - run: chmod +x ./gradlew
      - name: Package androidRelease
        uses: ilharp/sign-android-release@v1
        id: sign_app
        with:
          signingKey: ${{ secrets.SIGNING_STORE_BASE64 }}
          keyPassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
          keyAlias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref_name }}
      - uses: actions/upload-artifact@v4
        with:
          name: androidRelease
          path: ${{ steps.sign_app.outputs.signedFile }}
  package-windows:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: gradle/actions/setup-gradle@v4
      - run: chmod +x ./gradlew
      - name: package windowsAppImage
        run: ./gradlew :application:packageReleaseAppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref_name }}
      - uses: actions/upload-artifact@v4
        with:
          name: windowsAppImage
          path: application/build/compose/binaries/main-release/app/Yutori\ Application
      - name: package windowsMsi
        run: ./gradlew :application:packageReleaseMsi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref_name }}
      - uses: actions/upload-artifact@v4
        with:
          name: windowsMsi
          path: application/build/compose/binaries/main-release/msi/*
      - name: package windowsUberJar
        run: ./gradlew :application:packageReleaseUberJarForCurrentOS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref_name }}
      - uses: actions/upload-artifact@v4
        with:
          name: windowsUberJar
          path: application/build/compose/jars/*
  package-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: gradle/actions/setup-gradle@v4
      - run: chmod +x ./gradlew
      - name: package linuxAppImage
        run: ./gradlew :application:packageReleaseAppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref_name }}
      - uses: actions/upload-artifact@v4
        with:
          name: linuxAppImage
          path: application/build/compose/binaries/main-release/app/Yutori\ Application
      - name: package linuxDeb
        run: ./gradlew :application:packageReleaseDeb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref_name }}
      - uses: actions/upload-artifact@v4
        with:
          name: linuxDeb
          path: application/build/compose/binaries/main-release/deb/*
      - name: package linuxUberJar
        run: ./gradlew :application:packageReleaseUberJarForCurrentOS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref_name }}
      - uses: actions/upload-artifact@v4
        with:
          name: linuxUberJar
          path: application/build/compose/jars/*
  package-macos:
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: gradle/actions/setup-gradle@v4
      - run: chmod +x ./gradlew
      - name: package macosAppImage
        run: ./gradlew :application:packageReleaseAppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref_name }}
      - uses: actions/upload-artifact@v4
        with:
          name: macosAppImage
          path: application/build/compose/binaries/main-release/app/Yutori\ Application
      - name: package macosDmg
        run: ./gradlew :application:packageReleaseDmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref_name }}
      - uses: actions/upload-artifact@v4
        with:
          name: macosDmg
          path: application/build/compose/binaries/main-release/dmg/*
      - name: package macosUberJar
        run: ./gradlew :application:packageReleaseUberJarForCurrentOS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref_name }}
      - uses: actions/upload-artifact@v4
        with:
          name: macosUberJar
          path: application/build/compose/jars/*